- name: Copy nginx.repo
  copy: src=nginx.repo
        dest=/etc/yum.repos.d/nginx.repo
        owner=root
        group=root
        backup=yes

- name: Install nginx
  yum: name=nginx
       state=present